deployment:
  tasks:
    - export DEPLOYPATH=/home/kanpower/public_html
    - export REPOPATH=/home/kanpower/repositories/QR-Code-Generatorv2
    # Delete the .git directory to avoid conflicts with deployment.
    - /bin/rm -rf $REPOPATH/.git
 
