
deployment:
  tasks:
    # Define deployment and build paths
    - export DEPLOYPATH=/home/kanpower/public_html
    - export BUILDPATH=dist

    # Copy build files to the deployment path
    - /bin/cp -r $BUILDPATH/* $DEPLOYPATH
